### PR TITLE
Add a way to get a list of all errors that will happen when applying a template to a zone.

### PR DESCRIPTION
**Pull request by zaurky**

### CODE REVIEW

**Comment by arnoldblinn** [comment]
Hey....I love all the changes.  But I honestly don't know who this is making them....would be good to know.

**Comment by zaurky** [comment]
Hi @arnoldblinn,

I'm Olivier Roussy, developer at Gandi.net, and we are currently implementing the DNS Provider part of Domain Connect here.
I love the work you already did, but I need to have a way to get all errors at once.
I asked you a PR because I think it can be usefull for others, but I understand it makes a lot of changes in the codebase (even if the entry points do not change) so if you prefer not to, it's ok for me, we will handle it another way.

Regards,
    Olivier

**Comment by arnoldblinn** [comment]
Hey Oliver.  Nice to meet you.  I actually like the changes you are making, and am happy to have someone else work in  this project with me.  I wrote it slightly on a whim thinking it would be helpful.  I didn't anticipate someone needing multiple errors.  Since the errors aren't really reported to the user, just having an error exception thrown is usually enough.  That being said, Ill take a look at the pull.  There may be nothing wrong with this.  I'm just won't get to it till next week.....

**Comment by arnoldblinn** [comment]
So I took a look at this error processing code; it really complicates the code quite a bit.  And I'm not sure I fully understand the benefit.  Under normal circumstances a template will process normally, and an error should fail things.  Why is it needed to process all the errors at the same time?  I realize this is academically better.  Just not practically why it is better given the complexity it adds to the code.

I realize that an analogy is early compliers which would fail on the first error. It was somewhat painful to fix an error and run the compile again to find the next one.  But from a DNS Provider point of view, once an error it it fails to apply the template.  The Service Provider ought to be calling correctly, and will in the real world ensure this is the case.

If you feel strongly about the need for multiple errors, I have some ideas about how to implement this that may be a bit cleaner from the code point of view.

So I'll ask; why do you want all the errors from the process call?  What will this achieve for you?

Also, what is the point of "dryrun" and get_apply_template_errors?  If we REALLY need to get all the errors back, let's just modify apply_template to return all the errors (vs. raising an exception on the first one).

Net: If you really need all the errors back (still want to know why), I'll modify the code and make this happen without turning the code inside out.....

My 2 cents.

**Comment by zaurky** [comment]
Hi @arnoldblinn,

I thought about what you said friday this weekend, and you are right, that's not something we need when applying a template from a DNS provider point of view (that could be usefull when writing templates, but even so, not that much).

I went too fast when I tried to apply a template and got a full page of errors (lot of them with missing variables) and tough it would be easier to get them at once, but in the real process, that will not append.

I'm sorry I took you too much of your time for understanding that. Will be more carefull next time.

Thanks for your replies

**Comment by arnoldblinn** [comment]
I actually like all your other recommendations...keep them coming.

And....you might want to join the slack.  I don't have your email to add you.  Send it to me.  arnoldb@...

**Pull request closed without merging**
